#!/usr/bin/env php
<?php
error_reporting( E_ALL );
require_once __DIR__.'/../../../vendor/autoload.php';
require_once __DIR__.'/Client.php';
require_once __DIR__.'/HtmlToPlainText.php';

new UI_DevOutput();
new MailClient();

